import test from 'node:test';
import assert from 'node:assert/strict';
import {createCivetProcessor,civetEvidence} from './civet.js';
function rig(){const p=createCivetProcessor();let t=0;const feed=(v,n=1)=>{let r;for(let i=0;i<n;i++){r=p.ingest(typeof v==='function'?v(i):v,t);t=Math.round((t+.1)*10)/10;}return r;};p.calibrate('baseline');feed(22.24,51);p.calibrate('reference');feed(27.05,51);feed(22.24,40);return {p,feed,get t(){return t;}};}
test('small post-hold settling cannot permanently poison calibration',()=>{const {feed}=rig();const row=feed(21.89,600);assert.equal(row.usable,true);assert.equal(row.level_pct,0);});
test('brief missing packet recovers without pretending the missing interval is measured',()=>{const r=rig();const gap=r.p.ingest(22.24,r.t+.1);assert.equal(gap.gap,true);assert.equal(gap.acquisition_state,'recovering');assert.equal(gap.usable,false);let out;for(let i=1;i<=40;i++)out=r.p.ingest(22.24,r.t+.1+i*.1);assert.equal(out.usable,true);});
test('persistent drift warns and suppresses intensity but still resolves pressure pulses',()=>{const r=rig();r.feed(20,220);let row;for(let j=0;j<6;j++)row=r.feed(i=>20+Math.sin(Math.PI*i/10),11);assert.equal(row.usable,false);assert.ok(row.contractions_60s>=5);assert.equal(civetEvidence(row).contribution,0);assert.ok(['checking','recalibrate'].includes(row.acquisition_state));assert.equal(r.feed(22.24,140).usable,true);});
test('reconnect requires a deliberate rest/hold even after pressure returns',()=>{const r=rig();let row=r.p.ingest(22.24,r.t,{reconnected:true});for(let i=1;i<100;i++)row=r.p.ingest(22.24,r.t+i*.1);assert.equal(row.acquisition_state,'recalibrate');assert.equal(row.usable,false);});
test('settling times out visibly if the reference hold never releases',()=>{const p=createCivetProcessor();let row;p.calibrate('baseline');for(let i=0;i<51;i++)p.ingest(2,i/10);p.calibrate('reference');for(let i=51;i<410;i++)row=p.ingest(4,i/10);assert.equal(row.acquisition_state,'recalibrate');assert.match(row.acquisition_message,/did not settle/);});
