import test from 'node:test';
import assert from 'node:assert/strict';
import { stepVideoAnnouncement, videoAnnouncementState } from './videoPhaseAnnouncements.js';
const points=Array.from({length:400},(_,t)=>({t,phase:t<40?'build':t<80?'plateau':'approach',delta:12,plateau:80,approach:85,hrvUsable:true}));
function play(rate=1){let state=videoAnnouncementState(),cues=[];for(let wall=0;wall<=40000;wall+=250){const result=stepVideoAnnouncement(state,{points,time:wall/1000*rate,wall,rate});state=result.state;if(result.cue){cues.push(result.cue);state={...state,lastPhase:result.cue.type,spokenAt:wall};}}return cues;}
test('normal playback waits twelve media seconds and announces once per phase',()=>{const cues=play();assert.equal(cues[0].type,'build');assert.ok(cues[0].atMs>=12000);assert.equal(cues.filter(c=>c.type==='build').length,1);});
test('6x uses media dwell but real-time speech spacing and discards skipped phases',()=>{const cues=play(6);assert.equal(cues[0].type,'build');assert.ok(cues[0].atMs>=2500&&cues[0].atMs<12000);assert.ok(cues.slice(1).every((c,i)=>c.atMs-cues[i].atMs>=15000));assert.equal(cues.some(c=>c.type==='plateau'),false);assert.equal(cues[1].type,'approach');});
test('seek, pause and backward playback reset sustained observation',()=>{let state=stepVideoAnnouncement(videoAnnouncementState(),{points,time:0,wall:0}).state;let result=stepVideoAnnouncement(state,{points,time:100,wall:1000});assert.equal(result.cue,null);assert.equal(result.reset,true);result=stepVideoAnnouncement(result.state,{points,time:101,wall:2000,active:false});assert.equal(result.state.media,null);assert.equal(result.cue,null);result=stepVideoAnnouncement(state,{points,time:0,wall:20000,seeking:true});assert.equal(result.cue,null);});
test('crossed contradictory sample interrupts dwell even at fast playback',()=>{const rows=points.map(p=>({...p,phase:p.t===10?'unavailable':'build'}));let state=videoAnnouncementState();for(let wall=0;wall<=3500;wall+=250){const result=stepVideoAnnouncement(state,{points:rows,time:wall/1000*6,wall,rate:6});assert.equal(result.cue,null);state=result.state;}});
test('missing telemetry and stalled playback cannot announce stale phases',()=>{let state=videoAnnouncementState();for(let wall=0;wall<20000;wall+=1000){const result=stepVideoAnnouncement(state,{points:points.slice(0,4),time:wall/1000,wall});assert.equal(result.cue,null);state=result.state;}const result=stepVideoAnnouncement({...state,candidate:'build',since:0,wallSince:0,media:20},{points,time:20,wall:30000});assert.equal(result.cue,null);});
test('Body Exploration never announces climax',()=>{let state=videoAnnouncementState();for(let wall=0;wall<40000;wall+=250){const result=stepVideoAnnouncement(state,{points,time:80+wall/1000,wall,exploration:true});if(result.cue)assert.equal(result.cue.type,'high_load');state=result.state;}});
