export const LOCAL_VISION_STATUSES = ['visible', 'not_visible', 'uncertain'];

export const LOCAL_VISION_QUESTIONS = [
  {
    id: 'foley_catheter_visible',
    label: 'Foley catheter visible',
    category: 'object',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is the actual Foley catheter shaft or tip visibly present? Answer only from visible frame evidence. Use uncertain if the catheter is partially obscured or cannot be distinguished from other tubing/tools. Do not count a blue lubricant bottle, blue cap, tray-side blue object, detached tubing, or drainage bag/tubing away from the meatus as the catheter shaft/tip.',
    hallucinationWarning: 'Do not infer a catheter from procedure notes alone, and do not identify tray-side blue lubricant/prep material as a blue-tipped Foley.',
  },
  {
    id: 'foley_tubing_visible',
    label: 'Foley tubing visible',
    category: 'object',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is Foley/drainage tubing visibly present? Answer only from visible tubing evidence that is actually tubing, not a bottle/cap/object on the tray. Tubing away from the meatus is equipment/field evidence only; it does not prove insertion.',
    hallucinationWarning: 'Tubing visibility does not imply insertion, advancement, securement, or urine return. Do not identify a blue lubricant bottle or tray-side blue object as tubing.',
  },
  {
    id: 'statlock_visible',
    label: 'StatLock visible',
    category: 'object',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is a StatLock or adhesive catheter securement device visibly present? Do not infer this from tubing alone. Answer not_visible unless a distinct adhesive anchor/securement device is visible.',
    hallucinationWarning: 'Never infer StatLock from Foley tubing, yellow tubing, gloved hands, or procedure notes.',
  },
  {
    id: 'adhesive_securement_device_visible',
    label: 'Adhesive securement visible',
    category: 'object',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is an adhesive catheter securement device visibly present? Do not infer securement from tubing routing alone.',
    hallucinationWarning: 'Securement requires a visible adhesive/anchor device.',
  },
  {
    id: 'gloved_hands_visible',
    label: 'Gloved hands visible',
    category: 'object',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Are gloved hands visibly present in the field?',
    hallucinationWarning: 'Use uncertain if hand covering is not clear.',
  },
  {
    id: 'hands_touching_glans_or_meatus',
    label: 'Hands touching glans/meatus',
    category: 'action',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Are hands visibly touching or stabilizing the glans/meatus area?',
    hallucinationWarning: 'Do not infer meatal contact if anatomy is obscured.',
  },
  {
    id: 'catheter_tip_at_or_entering_meatus',
    label: 'Tip at/entering meatus',
    category: 'action',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is a catheter/tool tip visibly at, touching, aligned with, or entering the meatus? Use uncertain if the meatus or tip is blocked. The relevant evidence must be at the meatus, not tubing elsewhere and not a tray-side object. If the tip is only approaching but not at the meatus, answer uncertain and explain approach.',
    hallucinationWarning: 'Do not infer tip position from tubing elsewhere in the frame, procedure timing, or a blue lubricant/prep object on the tray.',
  },
  {
    id: 'visible_advancement_motion',
    label: 'Visible advancement motion',
    category: 'action',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Across the sampled frames, is there visible catheter/tool advancement through the meatus? Advancement requires visible tip or shaft movement entering/passing through the meatus across frames. Tool motion merely toward the meatus is approach, not advancement.',
    hallucinationWarning: 'Do not infer advancement from tubing presence alone.',
  },
  {
    id: 'tubing_routing_or_field_handling',
    label: 'Tubing/field handling',
    category: 'action',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Are hands visibly routing tubing, repositioning tubing, arranging drape/gauze, or handling the field without clear catheter advancement?',
    hallucinationWarning: 'Do not relabel tubing handling as securement or insertion.',
  },
  {
    id: 'urine_visible',
    label: 'Urine visible',
    category: 'object',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is urine visibly present in tubing, a container, or a bag? Do not infer urine confirmation from procedure stage.',
    hallucinationWarning: 'Urine confirmation requires visible fluid evidence.',
  },
  {
    id: 'balloon_inflation_visible',
    label: 'Balloon inflation visible',
    category: 'action',
    domain: 'foley',
    requiredFrameEvidence: true,
    prompt: 'Is balloon inflation visibly occurring, such as syringe/balloon-port interaction or clear inflation-related action?',
    hallucinationWarning: 'Do not infer balloon inflation from timing or catheter presence.',
  },
  {
    id: 'drape_applied_adjusted_or_removed',
    label: 'Drape applied/adjusted/removed',
    category: 'action',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Are drapes/towels/coverings visibly applied, adjusted, or removed?',
    hallucinationWarning: 'Use visible material movement only.',
  },
  {
    id: 'swab_gauze_syringe_lubricant_visible',
    label: 'Swab/gauze/syringe/lubricant visible',
    category: 'object',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Are swabs, gauze, a syringe, lubricant, or prep materials visibly present?',
    hallucinationWarning: 'Do not infer material type from procedure notes alone.',
  },
  {
    id: 'lubricant_or_syringe_visible',
    label: 'Lubricant or syringe visible',
    category: 'object',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Is lubricant, gel, or a syringe visibly present or being used near the field?',
    hallucinationWarning: 'Do not infer lubricant from shine alone unless the visual evidence is clear.',
  },
  {
    id: 'gauze_or_swab_visible',
    label: 'Gauze or swab visible',
    category: 'object',
    domain: 'procedure',
    requiredFrameEvidence: true,
    prompt: 'Is gauze, a swab, wipe, or applicator visibly present or used?',
    hallucinationWarning: 'Do not infer swabbing from notes alone.',
  },
  {
    id: 'anatomy_obscured_or_unclear',
    label: 'Anatomy obscured/unclear',
    category: 'absence',
    domain: 'general',
    requiredFrameEvidence: true,
    prompt: 'Is the relevant anatomy obscured, blocked, low-detail, blurred, or otherwise unclear?',
    hallucinationWarning: 'If anatomy is obscured, downstream state classifications should remain uncertain.',
  },
  {
    id: 'genital_state_visible',
    label: 'Genital state visible',
    category: 'state',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Is genital state visibly assessable in these frames? Use uncertain if blocked, cropped, or ambiguous.',
    hallucinationWarning: 'Do not infer genital state from notes or telemetry.',
  },
  {
    id: 'erection_state_visible',
    label: 'Erection state visible',
    category: 'state',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Is erection state visibly assessable? If assessable, attributes.state may be flaccid, partial_erection, erection, detumescence, or uncertain. If visibility is blocked or ambiguous, answer uncertain.',
    hallucinationWarning: 'Do not classify erection state when genital visibility is insufficient.',
  },
  {
    id: 'genital_visibility_obscured',
    label: 'Genital visibility obscured',
    category: 'absence',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Is genital visibility blocked, cropped, draped, blurred, or otherwise obscured?',
    hallucinationWarning: 'Obscured visibility blocks specific genital-state claims.',
  },
  {
    id: 'hand_contact_with_genitals_visible',
    label: 'Hand/genital contact visible',
    category: 'action',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Is hand contact with the genitals visibly present?',
    hallucinationWarning: 'Hand proximity alone is not hand/genital contact.',
  },
  {
    id: 'stroking_motion_visible',
    label: 'Stroking motion visible',
    category: 'action',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Across the sampled frames, is repeated hand/genital stroking motion visibly present? Use uncertain if motion is blocked, too subtle, or not visible across frames.',
    hallucinationWarning: 'Do not infer stroking from hand proximity alone.',
  },
  {
    id: 'stroking_rhythm_estimate',
    label: 'Stroking rhythm estimate',
    category: 'state',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'If stroking is visible, can a rough rhythm/intensity estimate be made from frame-to-frame motion? Use uncertain unless repeated motion is visible.',
    hallucinationWarning: 'Do not estimate rhythm from notes or single-frame contact.',
  },
  {
    id: 'grip_or_contact_change_visible',
    label: 'Grip/contact change visible',
    category: 'action',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Is a visible grip, hand position, or contact-location change present across frames?',
    hallucinationWarning: 'Do not infer stimulation changes from hand proximity alone.',
  },
  {
    id: 'pelvic_motion_visible',
    label: 'Pelvic motion visible',
    category: 'action',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Is pelvic lift/drop, thrust, shift, or other pelvic motion visibly present?',
    hallucinationWarning: 'Do not infer subjective experience from pelvic movement.',
  },
  {
    id: 'body_tension_or_relaxation_visible',
    label: 'Body tension/relaxation visible',
    category: 'state',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Is there visible body tension, bracing, relaxation, tremor, or posture change? Only report visible physical evidence.',
    hallucinationWarning: 'Do not infer pleasure, pain, orgasm, or intent.',
  },
  {
    id: 'leg_or_foot_position_visible',
    label: 'Leg/foot position visible',
    category: 'object',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Are leg or foot positions visible enough to assess?',
    hallucinationWarning: 'Do not infer lower-body response if feet/legs are off-camera.',
  },
  {
    id: 'toe_curling_or_foot_flexion_visible',
    label: 'Toe curling/foot flexion visible',
    category: 'action',
    domain: 'body_exploration',
    requiredFrameEvidence: true,
    prompt: 'Are toes/feet visibly curling, flexing, bracing, relaxing, or changing position across frames? Use uncertain if feet are not visible or motion cannot be confirmed.',
    hallucinationWarning: 'Do not infer orgasm/arousal from toe curling or foot movement.',
  },
  {
    id: 'ejaculation_or_fluid_release_visible',
    label: 'Fluid release visible',
    category: 'action',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Is ejaculation or visible fluid release present in these frames? This requires visible fluid release or new visible fluid presence.',
    hallucinationWarning: 'Do not infer fluid release from timing, posture, body state, or context.',
  },
  {
    id: 'visible_fluid_release_onset',
    label: 'Visible fluid release onset',
    category: 'action',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Is the onset frame/time of visible fluid release identifiable? Report attributes.onset_frame_id and attributes.onset_ms only if visible. Do not infer onset from body state or notes.',
    hallucinationWarning: 'Fluid release onset requires visible new release evidence.',
  },
  {
    id: 'fluid_release_pulse_count',
    label: 'Fluid release pulse count',
    category: 'state',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Are distinguishable repeated fluid release bursts visible across frames? If visible, estimate attributes.pulse_count. Use uncertain unless separate bursts can be visually distinguished.',
    hallucinationWarning: 'Do not count pulses from timing, posture, or assumed physiology.',
  },
  {
    id: 'fluid_stream_or_droplet_visible',
    label: 'Stream or droplet visible',
    category: 'object',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Is a visible fluid stream, droplet, arc, or landing trace present? Use only visible evidence.',
    hallucinationWarning: 'Do not infer a stream/droplet from wetness alone.',
  },
  {
    id: 'fluid_projection_distance_estimate',
    label: 'Projection distance estimate',
    category: 'state',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Can a visible fluid path or landing point support an approximate projection distance? Report attributes.distance_px if pixel distance is visually estimable. Report attributes.distance_cm only if a scale reference is available.',
    hallucinationWarning: 'Without scale calibration, real-world distance must remain unavailable.',
  },
  {
    id: 'fluid_trajectory_angle_estimate',
    label: 'Trajectory angle estimate',
    category: 'state',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Can the visible fluid path support an approximate trajectory angle in degrees? Use uncertain if no path/arc/landing trace is visible.',
    hallucinationWarning: 'Do not estimate angle from anatomy position alone.',
  },
  {
    id: 'fluid_velocity_proxy_estimate',
    label: 'Velocity proxy estimate',
    category: 'state',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Can frame-to-frame fluid movement support a velocity proxy? Report attributes.velocity_px_per_sec if pixel movement over time is visible. Report cm/sec only with scale calibration. Never report true force.',
    hallucinationWarning: 'Video without calibration can provide only a proxy, not physical force.',
  },
  {
    id: 'fluid_volume_proxy_estimate',
    label: 'Volume proxy estimate',
    category: 'state',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Can visible fluid amount be categorized as none, trace, low, moderate, high, or uncertain? This is a visual volume proxy only, not measured volume.',
    hallucinationWarning: 'Do not infer volume from orgasm/arousal/timing/context.',
  },
  {
    id: 'visible_fluid_present',
    label: 'Visible fluid present',
    category: 'object',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Is visible fluid/moisture present on anatomy, hands, material, tubing, or nearby surfaces? Identify only visible fluid evidence.',
    hallucinationWarning: 'Visible fluid is not automatically ejaculation.',
  },
  {
    id: 'post_ejaculation_state_visible',
    label: 'Post-fluid state visible',
    category: 'state',
    domain: 'masturbation',
    requiredFrameEvidence: true,
    prompt: 'Is a visible post-fluid/post-ejaculation state present, such as visible fluid plus cleanup or clear post-event evidence?',
    hallucinationWarning: 'Do not infer post-ejaculation state from timing or posture alone.',
  },
  {
    id: 'post_event_fluid_presence',
    label: 'Post-event fluid presence',
    category: 'object',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Is fluid visibly present after a release event or on nearby material/anatomy? Do not infer this from a presumed event.',
    hallucinationWarning: 'Post-event fluid presence requires visible fluid evidence.',
  },
  {
    id: 'cleanup_or_wipe_visible',
    label: 'Cleanup or wipe visible',
    category: 'action',
    domain: 'fluid_dynamics',
    requiredFrameEvidence: true,
    prompt: 'Is cleanup or wiping visibly occurring, or are cleanup materials visibly being used? Use visible evidence only.',
    hallucinationWarning: 'Static towels/tissues are not cleanup action unless use is visible.',
  },
  {
    id: 'cleanup_material_visible',
    label: 'Cleanup material visible',
    category: 'object',
    domain: 'general',
    requiredFrameEvidence: true,
    prompt: 'Are cleanup materials such as towel, tissue, wipe, pad, or gauze visibly present or used?',
    hallucinationWarning: 'Do not infer cleanup intent from static material alone.',
  },
  {
    id: 'lubricant_visible',
    label: 'Lubricant visible',
    category: 'object',
    domain: 'general',
    requiredFrameEvidence: true,
    prompt: 'Is lubricant, gel, bottle, shine consistent with lubricant, or lubricant application visibly present?',
    hallucinationWarning: 'Use uncertain if shine could be lighting or moisture.',
  },
  {
    id: 'device_or_toy_visible',
    label: 'Device/toy visible',
    category: 'object',
    domain: 'general',
    requiredFrameEvidence: true,
    prompt: 'Is a device, toy, sleeve, vibrator, catheter, pump, or other session-relevant object visibly present?',
    hallucinationWarning: 'Do not identify a specific device type unless visually supported.',
  },
];

export function getQuestionBank() {
  return LOCAL_VISION_QUESTIONS.map((question) => ({
    ...question,
    allowedAnswers: LOCAL_VISION_STATUSES,
  }));
}

export function normalizeQuestionIds(ids = []) {
  const known = new Map(getQuestionBank().map((question) => [question.id, question]));
  const requested = Array.isArray(ids) && ids.length ? ids : [...known.keys()];
  const unique = [];
  for (const id of requested) {
    const key = String(id || '').trim();
    if (known.has(key) && !unique.includes(key)) unique.push(key);
  }
  return unique;
}

export function questionsForIds(ids = []) {
  const known = new Map(getQuestionBank().map((question) => [question.id, question]));
  return normalizeQuestionIds(ids).map((id) => known.get(id)).filter(Boolean);
}
